apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8stoken-deployment-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: k8stoken
  namespace: default  # 这里是绑定到 default 命名空间中的 k8stoken ServiceAccount
roleRef:
  kind: Role
  name: k8stoken-deployment-role
  apiGroup: rbac.authorization.k8s.io
